#!/bin/bash
# ============================================================
# JETSON STEP J05 — Set up token auto-refresh cron job
# Run this ON THE JETSON (172.18.3.202)
#
# The runner.py reads /opt/frs/device_token.txt on every POST.
# This cron refreshes the token every 25 min before it
# expires (ACCESS_TOKEN_TTL_MINUTES=30 in backend .env).
# ============================================================
set -e

VM_IP="172.20.100.222"

echo ""
echo "=================================================="
echo " JETSON J05: Set up token refresh cron"
echo "=================================================="
echo ""

# ── Write the refresh script ──────────────────────────────
echo "[1/3] Writing /opt/frs/refresh_token.sh ..."

cat > /opt/frs/refresh_token.sh << SCRIPT
#!/bin/bash
# Auto-generated by J05_setup_token_cron.sh
# Refreshes the device auth token from the backend

VM_IP="${VM_IP}"
TOKEN_FILE="/opt/frs/device_token.txt"
LOG="/opt/frs/token_refresh.log"

log() {
  echo "\$(date '+%Y-%m-%d %H:%M:%S') \$1" >> "\$LOG"
}

log "Refreshing token..."

# Try API mode first
LOGIN=\$(curl -s --max-time 10 \
  -X POST "http://\${VM_IP}:8080/api/auth/login" \
  -H "Content-Type: application/json" \
  -d '{"email":"admin@company.com","password":"admin123"}' 2>/dev/null || echo "")

TOKEN=\$(echo "\$LOGIN" | python3 -c \
  "import sys,json; d=json.load(sys.stdin); print(d.get('accessToken',''))" 2>/dev/null || echo "")

if [ -z "\$TOKEN" ]; then
  # Fallback to Keycloak
  KC=\$(curl -s --max-time 10 \
    -X POST "http://\${VM_IP}:9090/realms/attendance/protocol/openid-connect/token" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d "client_id=attendance-frontend&username=admin@company.com&password=admin123&grant_type=password" 2>/dev/null || echo "")
  TOKEN=\$(echo "\$KC" | python3 -c \
    "import sys,json; d=json.load(sys.stdin); print(d.get('access_token',''))" 2>/dev/null || echo "")
fi

if [ -n "\$TOKEN" ]; then
  echo "\$TOKEN" > "\$TOKEN_FILE"
  chmod 600 "\$TOKEN_FILE"
  log "Token refreshed OK (\${#TOKEN} chars)"
else
  log "ERROR: Token refresh failed"
fi

# Trim log file to last 200 lines
tail -200 "\$LOG" > "\$LOG.tmp" && mv "\$LOG.tmp" "\$LOG"
SCRIPT

chmod +x /opt/frs/refresh_token.sh
echo "  ✅ refresh_token.sh written"

# ── Test the refresh script works now ─────────────────────
echo ""
echo "[2/3] Testing refresh script..."
/opt/frs/refresh_token.sh

if [ -s /opt/frs/device_token.txt ]; then
  echo "  ✅ Test refresh successful"
else
  echo "  ❌ Refresh script failed — check backend is running"
  exit 1
fi

# ── Install cron job ──────────────────────────────────────
echo ""
echo "[3/3] Installing cron job (every 25 minutes)..."

# Remove existing frs token refresh entries
crontab -l 2>/dev/null | grep -v "refresh_token.sh" > /tmp/existing_cron.txt || true

# Add new entry
echo "*/25 * * * * /opt/frs/refresh_token.sh" >> /tmp/existing_cron.txt
crontab /tmp/existing_cron.txt
rm /tmp/existing_cron.txt

echo "  ✅ Cron installed"
echo ""
echo "  Current crontab:"
crontab -l | grep "refresh_token" | sed 's/^/  /'

echo ""
echo "  Log file: /opt/frs/token_refresh.log"
echo ""
echo "=================================================="
echo " ✅ JETSON J05 COMPLETE"
echo "=================================================="
echo ""
echo "  Token will auto-refresh every 25 minutes."
echo ""
echo "Next: Run J06_start_runner.sh"
echo ""
